# SPDX-FileCopyrightText: 2023 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: MIT

line-length = 79

[lint]
select = ["ALL"]
ignore = ["S603", "S607", "S311", "T201"]
unfixable = ["F401"]

[lint.pydocstyle]
convention = "google"
